name: GolangCI
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Update dependencies
        run: go mod tidy -go=1.20

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
